spring:
  #mysql的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seek_food_interaction
    username: root
    password: 439176




interaction:
  self:
    params: 
      rules:
        bitmap-per-x-number: 100
        report-image-dest: "D:/home/admin/image/employee/person"
    redis:
      key:
        interaction-like-merchant:
          name: "interaction:like:merchant:"
          duration: null
        interaction-like-first-comment:
          name: "interaction:like:first:comment"
          duration: null
        interaction-like-second-comment:
          name: "interaction:like:second:comment:"
          duration: null
        interaction-collect-merchant:
          name: "interaction:collect:merchant:"
          duration: null
        employee-insert-cooldown:
          name: "employee:insert:cooldown:"
          duration: 5
        employee-id-count:
          name: "employee:id:count"
          duration: null
        employee-message-caffeine:
          name: "employee:message:caffeine:"
          duration: 600
      stream:
        oldFileStream:
          name: employee:stream:old:file
          key-name: fileName
          consumer:
            group-name: DeleteGroup
            number: 1
    jvm-caffeine:
      employee:
        max-size: 100000
        expire-time: 300