spring:
  #mysql的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seek_food_merchant
    username: root
    password: 439176

merchant:
  self:
    params: 
      rules:
        merchant-name-max: 15
        proof-image-number-max: 6
        show-image-number-max: 10
        show-description-max: 300
        merchant-addr-max: 60
        master-image-dest: "D:/home/admin/image/merchant/master"
        proof-image-dest: "D:/home/admin/image/merchant/proof"
        show-image-dest: "D:/home/admin/image/merchant/show"
        home-image-dest: "D:/home/admin/image/merchant/home"
    redis:
      key:
        merchant-register-opt:
          name: "merchant:register:opt:"
          duration: 60
        merchant-login-opt:
          name: "merchant:login:opt:"
          duration: 60
        merchant-update-password-opt:
          name: "merchant:update:password:opt:"
          duration: 60
        merchant-delete-opt:
          name: "merchant:delete:opt:"
          duration: 60
        merchant-login-password-cooldown:
          name: "merchant:login:password:cooldown:"
          duration: 3
        merchant-login-refresh-cooldown:
          name: "merchant:login:password:refresh:"
          duration: 432000
        merchant-update-password-cooldown:
          name: "merchant:update:password:cooldown:"
          duration: 6
        merchant-update-message-cooldown:
          name: "merchant:update:message:cooldown:"
          duration: 3
        merchant-add-proof-cooldown:
          name: "merchant:add:proof:cooldown:"
          duration: 3
        merchant-add-show-cooldown:
          name: "merchant:add:show:cooldown:"
          duration: 3
        merchant-remove-proof-cooldown:
          name: "merchant:remove:proof:cooldown:"
          duration: 3
        merchant-remove-show-cooldown:
          name: "merchant:remove:show:cooldown:"
          duration: 3
        merchant-replace-proof-cooldown:
          name: "merchant:update:proof:cooldown:"
          duration: 3
        merchant-replace-show-cooldown:
          name: "merchant:update:show:cooldown:"
          duration: 3
        merchant-update-master-cooldown:
          name: "merchant:update:master:cooldown:"
          duration: 6
        merchant-update-home-cooldown:
          name: "merchant:update:home:cooldown:"
          duration: 3
        merchant-delete-cooldown:
          name: "merchant:delete:cooldown:"
          duration: 432000
        merchant-update-open-cooldown:
          name: "merchant:update:open:cooldown:"
          duration: 30
        merchant-get-distance-cooldown:
          name: "merchant:get:distance:cooldown:"
          duration: 3
        merchant-id-count:
          name: "merchant:id:count"
          duration: null
        merchant-master-is-set:
          name: "merchant:master:is:set"
          duration: null
        merchant-message-caffeine:
          name: "merchant:message:caffeine:"
          duration: 600
        merchant-phone-caffeine:
          name: "merchant:phone:caffeine:"
          duration: 600
        merchant-es-sync-record:
          name: "merchant:es:sync:record:"
          duration: null
      stream:
        oldFileStream:
          name: merchant:stream:old:file
          key-name: fileName
          consumer:
            group-name: DeleteGroup
            number: 1
        esSyncStream:
          name: merchant:stream:es:sync
          key-name: merchantId
          consumer:
            group-name: SyncGroup
            number: 1
    jvm-caffeine:
      merchant:
        max-size: 100000
        expire-time: 300
      phone-number:
        max-size: 100000
        expire-time: 600
    es:
      merchant:
        index-name: merchant
        merchant-id: merchant_id
        merchant-name: merchant_name
        merchant-collect-amount: merchant_collect_amount
        merchant-order-amount: merchant_order_amount
        merchant-home-image: merchant_home_image
        merchant-location: merchant_location
        is-open: is_open
        is-delete: is_delete
    scheduled-druation:
      es-sync: 3000











