spring:
  #mysql的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seek_food_order
    username: root
    password: 439176



order:
  self:
    params: 
      rules:
        delivery-address-max: 60
        every-km-cost: 1
        state-number-max: 6
    redis:
      key:
        order-insert-lock:
          name: "order:insert:lock:"
          duration: null
        order-get-simple-cooldown:
          name: "order:get:simple:cooldown:"
          duration: 1
        order-get-simple-by-state-cooldown:
          name: "order:get:simple:state:cooldown:"
          duration: 1
        order-refund-cooldown:
          name: "order:refund:cooldown:"
          duration: 3
        order-merchant-reject-cooldown:
          name: "order:merchant:reject:cooldown:"
          duration: 3
        order-merchant-ack-cooldown:
          name: "order:merchant:ack:cooldown:"
          duration: 3
        order-merchant-make-cooldown:
          name: "order:merchant:make:cooldown:"
          duration: 3
        order-rider-accept-cooldown:
          name: "order:rider:accept:cooldown:"
          duration: 3
        order-rider-ack-cooldown:
          name: "order:rider:ack:cooldown:"
          duration: 3
        order-rider-delivery-cooldown:
          name: "order:rider:delivery:cooldown:"
          duration: 3
        order-user-receive-cooldown:
          name: "order:user:receive:cooldown:"
          duration: 3
        order-rider-get-es-order-cooldown:
          name: "order:rider:get:es:order:cooldown:"
          duration: 1
        order-comment-select-cooldown:
          name: "order:comment:select:cooldown:"
          duration: 1
        order-id-count:
          name: "order:id:count"
          duration: null
        order-message-caffeine:
          name: "order:message:caffeine:"
          duration: 600
    es:
      rider-order:
        index-name: rider_order
        orderId: order_id
        merchantId: merchant_id
        deliveryAddress: delivery_address
        deliveryLatLon: delivery_lat_lon
        mealContent: meal_content
        number: number
        riderCost: rider_cost
        accept: is_accept
    jvm-caffeine:
      order:
        max-size: 100000
        expire-time: 300



